Task 2. CLI-grep. Дима Орехов
DimaOrekhov/SoftwareDesignITMO2020 pull request #3
Opened 2020-06-28 14:27 UTC by DimaOrekhov

**Рассмотренные библиотеки:**

- Apache Commons CLI

Один из стандартных инструментов для парсинга аргументов в Java. Удобная установка, широко распространен, а поэтому много различной информации в интернете.
- JSAP

Судя по туториалу, очень удобный и достаточно мощный инструмент предназначенный именно для парсинга аргументов. 

- picocli

	Мощная библиотека для создания консольных приложений. Понравилось, что аргументы можно различно типизировать, обширно используются аннотации.

**Выбор:**

	Выбор остановился на Apache Commons CLI. Для JSAP не нашел удобного способа установки через gradle. picocli, кажется, overkill для моих целей.

2020-06-30 19:20 UTC, yurii-litvinov requested changes
- Надо ещё CI к репозиторию прикрутить, в котором бы гонялись тесты в том числе и  на новую функциональность
- Кстати, довольно странно выкладывать gradlew, не выкладывая сам Gradle Wrapper. gradlew --- это на самом деле скрипт, который запускает .jar-ник в папке gradle, который качает gradle и запускает его. gradlew без jar-ника бесполезен.
- Из консоли не запускается без дополнительных усилий, не используется gradle application plugin и не прописан запускаемый класс в манифесте jar-ника
- Ещё надо на отрицательный аргумент -A ругаться, хорошая диагностика --- это всегда хорошо

В общем, надо немного поправить. Можно после экзамена

2020-06-30 19:20 UTC, yurii-litvinov commented on CLI/src/main/java/ru/itmo/mit/cli/execution/EnvironmentUtils.java
> +     * @param filePathAsString
Пустые комментарии не очень полезны, лучше их вовсе не писать, или написать уж

2020-06-30 19:20 UTC, yurii-litvinov commented on CLI/src/test/java/ru/itmo/mit/cli/ShellTest.java
> +        //expectedOutStream.write("hello world\n".getBytes(charset));
И закомментированный код --- это плохо :)

2020-07-02 22:16 UTC, DimaOrekhov commented on CLI/src/main/java/ru/itmo/mit/cli/execution/EnvironmentUtils.java
> +     * @param filePathAsString
Поправил в тех файлах, что были в коммите, в остальных пока решил не править, чтобы не засорять пул реквест.

2020-07-02 22:16 UTC, DimaOrekhov commented on CLI/src/test/java/ru/itmo/mit/cli/ShellTest.java
> +        //expectedOutStream.write("hello world\n".getBytes(charset));
Поправил

2020-07-02 22:18 UTC, DimaOrekhov commented
1. Добавил CI через GitHub actions и gradle
2. Теперь выкладываю wrapper
3. Задействовал плагин application, теперь можно запустить приложение из консоли
4. Добавил обработку отрицательного аргумента и тест на этот случай

2020-07-03 15:20 UTC, yurii-litvinov approved these changes
👍

2021-09-06 14:00 UTC, merged